### ISSUE TITLE
UniverseID of packets is always 0

### ISSUE THREAD

**Issue by joedemax** [iKadmium/kadmium-sacn#1]
Hey mate,

Trying to use your library for a project. Problem I have ATM is no matter which universe I listen for, when a packet arrives the UniverseID property is always 0. Any ideas?

**Comment by iKadmium** [comment]
Hey there,

Just going through the code right now and I see the problem. The Universe
ID is getting parsed and then not stored, haha. Oops. I'll try to get that
fixed up ASAP.

**Comment by iKadmium** [comment]
Closing this as it's getting rewritten. I'll make sure I've got a test for this.
