### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MikeCodesDotNET** [iKadmium/kadmium-sacn#2]
It'd be super useful to understand what license does this project use? Fingers crossed for MIT!

**Comment by iKadmium** [comment]
Honestly, I hadn't really given it much thought. This hasn't been updated
in a while and I moved on to a different implementation - I'm more than
happy to call this one MIT.

**Comment by iKadmium** [comment]
Closing this as it's getting rewritten. There will be a license file for it.
